### ISSUE TITLE
update [Slider] default values

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-components#230]
| Name   | Type   | Default Value | Required | Description               |
| ------ | ------ | :-----------: | :------: | ------------------------- |
| width  | number |      n/a      |          | The width of the slider.  |
| height | number |       0       |          | The height of the slider. |

| Name  | Type   | Default Value | Description                                                                                                                       |
| :---- | :----- | :-----------: | --------------------------------------------------------------------------------------------------------------------------------- |
| min   | number |      `0`      | Sets the minimum slider value. This value is set only if it is less than the slider's maximum value. The default value is `0`.    |
| max   | number |      `1`      | Sets the maximum slider value. This value is set only if it is greater than the slider's minimum value. The default value is `1`. |
| value | number |      n/a      | Sets the slider value. The value will be clamped within the current minimum and maximum range.                                    |

**Comment by grozdanov** [comment]
MXSCOMP-79

**Comment by darek607** [comment]
@grozdanov @pleszkiewicz  if the `width` and `height` is not specified the scroll should be invisible? On Android and iOS for some components we have specified some default values, e.g. for Slider we have: `width=0.5` and height=`0.018`.

**Comment by pleszkiewicz** [comment]
I confirm that we have default values for `width` and `height`. This way it's possible to create ```<Slider />``` without any attributes (iOS, Android).

**Comment by grzegorzdec** [comment]
`value` default value should be 0 instead of `n/a` - it makes more sense
android size: 1

**Comment by pleszkiewicz** [comment]
@grzegorzdec What if `min=1` and `max=2`? The default value should be set to `min`.

**Comment by darek607** [comment]
I agree with Paweł, just set in docs that default value = min

**Comment by panwrona** [comment]
Right now when we specify min=1 & max=2, the behavior is following:
- On Lumin, initially the value is set to 0, we can slide between 1 and 2 (from the center of the slider)
- On Android, initially the value is set to 0, when we tap on the slider, it changes value to 1 and the sliding circle is visible
- On iOS, we can change the value between 0 and 2 for the whole time

Either we fix all of this on each platform, or we specify the conditions in documentation, to show developer that when the min and max is changed, the value also needs to be set between those, otherwise weird behavior can be expected

**Comment by kpiascik** [comment]
we should make sure this:  min <= value <=max

**Comment by panwrona** [comment]
Resolved: https://github.com/magic-script/magic-script-components-react-native/pull/458
